require("dotenv").config();
const express = require("express"), session = require("express-session"), bcrypt = require("bcryptjs"), path = require("path"), fs = require("fs");
const app = express(), PORT = process.env.PORT || 3000, dataDir = path.join(__dirname, "data"), dbFile = path.join(dataDir, "database.json");
fs.mkdirSync(dataDir, { recursive: true });
const empty = { users: [], services: [], orders: [], topups: [] };
let db; try { db = fs.existsSync(dbFile) ? JSON.parse(fs.readFileSync(dbFile, "utf8")) : empty } catch { db = empty }
for (const k of Object.keys(empty)) if (!Array.isArray(db[k])) db[k] = [];
const save = () => { const t = dbFile + ".tmp"; fs.writeFileSync(t, JSON.stringify(db, null, 2)); fs.renameSync(t, dbFile) };
const next = a => a.length ? Math.max(...a.map(x => Number(x.id) || 0)) + 1 : 1, now = () => new Date().toISOString();
const byId = id => db.users.find(u => u.id === Number(id));
if (!db.services.length) {
    db.services = [
        { id: 1, game: "Roblox - Chưa chọn game", title: "Cày level cơ bản", description: "Dịch vụ mẫu. Thay bằng game Roblox cụ thể của bạn.", price: 50000, eta: "1-2 ngày", active: 1 },
        { id: 2, game: "Roblox - Chưa chọn game", title: "Cày nhiệm vụ", description: "Dịch vụ mẫu cho hệ thống. Bạn có thể đổi tên, mô tả và giá.", price: 70000, eta: "1-3 ngày", active: 1 },
        { id: 3, game: "Roblox - Chưa chọn game", title: "Gói cày theo yêu cầu", description: "Khách gửi yêu cầu riêng để shop báo giá.", price: 100000, eta: "Liên hệ", active: 1 }]; save()
}
(async () => { const e = process.env.ADMIN_EMAIL, p = process.env.ADMIN_PASSWORD; if (e && p && !db.users.some(u => u.email === e.trim().toLowerCase())) { db.users.push({ id: next(db.users), name: "Administrator", email: e.trim().toLowerCase(), password: await bcrypt.hash(p, 12), balance: 0, is_admin: 1, created_at: now() }); save() } })();
app.use(express.urlencoded({ extended: true })); app.use(express.json()); app.use(session({ secret: process.env.SESSION_SECRET || "dev-only-change-me", resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 604800000 } })); app.use(express.static(path.join(__dirname, "public")));
const me = req => { if (!req.session.userId) return null; const u = byId(req.session.userId); return u ? { id: u.id, name: u.name, email: u.email, balance: u.balance, is_admin: u.is_admin } : null };
const login = (req, res, next) => me(req) ? next() : res.status(401).json({ error: "Bạn cần đăng nhập." });
const admin = (req, res, next) => { const u = me(req); u && u.is_admin ? next() : res.status(403).json({ error: "Không có quyền admin." }) };
app.get("/api/me", (req, res) => res.json({ user: me(req) }));
app.get("/api/services", (req, res) => res.json({ services: db.services.filter(s => s.active) }));
app.post("/api/register", async (req, res) => { const { name, email, password } = req.body; if (!name || !email || !password || password.length < 6) return res.status(400).json({ error: "Tên, email và mật khẩu tối thiểu 6 ký tự là bắt buộc." }); const em = email.trim().toLowerCase(); if (db.users.some(u => u.email === em)) return res.status(409).json({ error: "Email đã tồn tại." }); const u = { id: next(db.users), name: name.trim(), email: em, password: await bcrypt.hash(password, 12), balance: 0, is_admin: 0, created_at: now() }; db.users.push(u); save(); req.session.userId = u.id; res.json({ ok: true }) });
app.post("/api/login", async (req, res) => { const em = (req.body.email || "").trim().toLowerCase(), u = db.users.find(x => x.email === em); if (!u || !(await bcrypt.compare(req.body.password || "", u.password))) return res.status(401).json({ error: "Email hoặc mật khẩu không đúng." }); req.session.userId = u.id; res.json({ ok: true }) });
app.post("/api/logout", (req, res) => req.session.destroy(() => res.json({ ok: true })));
app.post("/api/orders", login, (req, res) => { const { serviceId, gameAccount, note = "" } = req.body, u = byId(req.session.userId), s = db.services.find(x => x.id === Number(serviceId) && x.active); if (!s) return res.status(404).json({ error: "Dịch vụ không tồn tại." }); if (!gameAccount?.trim()) return res.status(400).json({ error: "Vui lòng nhập thông tin tài khoản game." }); if (u.balance < s.price) return res.status(400).json({ error: "Số dư không đủ. Hãy nạp tiền trước." }); u.balance -= s.price; const o = { id: next(db.orders), user_id: u.id, service_id: s.id, game_account: gameAccount.trim(), note: note.trim(), price: s.price, status: "pending", created_at: now() }; db.orders.push(o); save(); res.json({ ok: true, orderId: o.id }) });
app.get("/api/orders", login, (req, res) => res.json({ orders: db.orders.filter(o => o.user_id === req.session.userId).sort((a, b) => b.id - a.id).map(o => { const s = db.services.find(x => x.id === o.service_id) || {}; return { ...o, game: s.game || "N/A", title: s.title || "N/A" } }) }));
app.post("/api/topups", login, (req, res) => { const { provider, denomination, serial, code } = req.body; if (!["Viettel", "MobiFone", "VinaPhone", "Vietnamobile"].includes(provider) || !Number(denomination) || !serial || !code) return res.status(400).json({ error: "Thông tin thẻ chưa đầy đủ." }); const t = { id: next(db.topups), user_id: req.session.userId, provider, denomination: Number(denomination), serial: serial.trim(), code: code.trim(), status: "pending", created_at: now() }; db.topups.push(t); save(); res.json({ ok: true, topupId: t.id, message: "Đã ghi nhận yêu cầu. Bản demo chưa kết nối cổng thẻ thật." }) });
app.get("/api/topups", login, (req, res) => res.json({ topups: db.topups.filter(t => t.user_id === req.session.userId).sort((a, b) => b.id - a.id).map(({ code, ...x }) => x) }));
app.get("/api/admin/orders", admin, (req, res) => res.json({ orders: db.orders.sort((a, b) => b.id - a.id).map(o => { const u = byId(o.user_id) || {}, s = db.services.find(x => x.id === o.service_id) || {}; return { ...o, email: u.email || "", game: s.game || "", title: s.title || "" } }) }));
app.patch("/api/admin/orders/:id", admin, (req, res) => { if (!["pending", "processing", "completed", "cancelled"].includes(req.body.status)) return res.status(400).json({ error: "Trạng thái không hợp lệ." }); const o = db.orders.find(x => x.id === Number(req.params.id)); if (!o) return res.status(404).json({ error: "Không tìm thấy đơn." }); o.status = req.body.status; save(); res.json({ ok: true }) });
app.get("/api/admin/topups", admin, (req, res) => res.json({ topups: db.topups.sort((a, b) => b.id - a.id).map(({ code, ...t }) => ({ ...t, email: (byId(t.user_id) || {}).email || "" })) }));
app.patch("/api/admin/topups/:id", admin, (req, res) => { const st = req.body.status; if (!["pending", "approved", "rejected"].includes(st)) return res.status(400).json({ error: "Trạng thái không hợp lệ." }); const t = db.topups.find(x => x.id === Number(req.params.id)); if (!t) return res.status(404).json({ error: "Không tìm thấy giao dịch." }); if (t.status === "approved" && st !== "approved") return res.status(400).json({ error: "Giao dịch đã duyệt, không thể hoàn tác." }); if (st === "approved" && t.status !== "approved") { const u = byId(t.user_id); if (u) u.balance += t.denomination } t.status = st; save(); res.json({ ok: true }) });
app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
}); app.listen(PORT, () => console.log(`Shop running: http://localhost:${PORT}`));